---
- name: "Preflight Checks"
  include_tasks: "00-preflight-checks.yml"
  
- name: "Install dependencies"
  include_tasks: "01-dependencies.yml"
  
- name: "Generate CA"
  include_tasks: "02-ca.yml"
  when: generate.ca

- name: "Generate Certificate"
  include_tasks: "03-certificate.yml"
  when: generate.certificate

- name: "Remove dependencies"
  include_tasks: "04-cleanup-dependencies.yml"
